//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervallo.DefaultPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervallo.DefaultPlugins.Properties.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   VSQXファイルの読み込みを中断しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqLoader_CancelLoad {
            get {
                return ResourceManager.GetString("VsqLoader_CancelLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VSQXファイルの読み込みに失敗しました。ファイル形式が古いか、壊れている可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqLoader_FailLoadFile {
            get {
                return ResourceManager.GetString("VsqLoader_FailLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VSQXファイルから音階データを読み込みます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqxLoader_Description {
            get {
                return ResourceManager.GetString("VsqxLoader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqxTrackSelectWindow_Cancel {
            get {
                return ResourceManager.GetString("VsqxTrackSelectWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トラックが複数検出されました。読み込むトラックを選択してください: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqxTrackSelectWindow_Description {
            get {
                return ResourceManager.GetString("VsqxTrackSelectWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqxTrackSelectWindow_OK {
            get {
                return ResourceManager.GetString("VsqxTrackSelectWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VsqxLoader トラックの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VsqxTrackSelectWindow_Title {
            get {
                return ResourceManager.GetString("VsqxTrackSelectWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WORLDを利用して音声の解析・生成を行います に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WorldOperator_Description {
            get {
                return ResourceManager.GetString("WorldOperator_Description", resourceCulture);
            }
        }
    }
}
