//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervallo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervallo.Properties.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   wavファイルの読み込みに失敗しました。
        ///読み込もうとしているwavファイルを別のプログラムで開いている等、何らかの理由でwavファイルが読み込めなくなっている可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CannodLoadWaveFile {
            get {
                return ResourceManager.GetString("Error_CannodLoadWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込みプラグインの読み込みに失敗しました。音声からの音階読み込みのみ利用可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CannotLoadScaleLoader {
            get {
                return ResourceManager.GetString("Error_CannotLoadScaleLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込み中にエラーが発生しました
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_RaiseLoadScaleError {
            get {
                return ResourceManager.GetString("Error_RaiseLoadScaleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインの読み込み中にエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_RaisePluginLoadError {
            get {
                return ResourceManager.GetString("Error_RaisePluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サポートされていない形式のwavファイルです。
        ///このアプリケーションではモノラルのPCMのみサポートしています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_UnsupportedWaveFile {
            get {
                return ResourceManager.GetString("Error_UnsupportedWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析プラグインの読み込みに失敗しました。Pluginsフォルダに壊れたファイルがないか確認の上、アプリケーションを再起動してください
        ///(再度アプリケーションをダウンロードの上、DefaultPlugins以外が存在しない状態での起動を推奨します) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fatal_CannotLoadAudioOperator {
            get {
                return ResourceManager.GetString("Fatal_CannotLoadAudioOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き出し(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Export {
            get {
                return ResourceManager.GetString("MainMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データの読み込み(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScale {
            get {
                return ResourceManager.GetString("MainMenu_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイルから読み込む(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScaleFromWave {
            get {
                return ResourceManager.GetString("MainMenu_LoadScaleFromWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ManipulationMenu {
            get {
                return ResourceManager.GetString("MainMenu_ManipulationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_OpenFile {
            get {
                return ResourceManager.GetString("MainMenu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原音の再生・停止(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Preview {
            get {
                return ResourceManager.GetString("MainMenu_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析プラグインの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadAudioOperator {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadAudioOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込みプラグインの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadScaleLoader {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadScaleLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   waveファイルの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadWaveFile {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_Cancel {
            get {
                return ResourceManager.GetString("MessageBoxWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_ExceptionInfoHeader {
            get {
                return ResourceManager.GetString("MessageBoxWindow_ExceptionInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_No {
            get {
                return ResourceManager.GetString("MessageBoxWindow_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_OK {
            get {
                return ResourceManager.GetString("MessageBoxWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleError {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleInformation {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleQuestion {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleWarning {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい(_Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_Yes {
            get {
                return ResourceManager.GetString("MessageBoxWindow_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_AnalyzingWave {
            get {
                return ResourceManager.GetString("ProgressMessage_AnalyzingWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル出力中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_ExportWave {
            get {
                return ResourceManager.GetString("ProgressMessage_ExportWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadScale {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadWave {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadWave", resourceCulture);
            }
        }
    }
}
