//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervallo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervallo.Properties.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Library License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_LibraryLicense {
            get {
                return ResourceManager.GetString("AboutWindow_LibraryLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_License {
            get {
                return ResourceManager.GetString("AboutWindow_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_OK {
            get {
                return ResourceManager.GetString("AboutWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイルの読み込みに失敗しました。
        ///読み込もうとしているwavファイルを別のプログラムで開いている等、何らかの理由でwavファイルが読み込めなくなっている可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CannodLoadWaveFile {
            get {
                return ResourceManager.GetString("Error_CannodLoadWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込みプラグインの読み込みに失敗しました。音声からの音階読み込みのみ利用可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_CannotLoadScaleLoader {
            get {
                return ResourceManager.GetString("Error_CannotLoadScaleLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込み中にエラーが発生しました
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_RaiseLoadScaleError {
            get {
                return ResourceManager.GetString("Error_RaiseLoadScaleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインの読み込み中にエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_RaisePluginLoadError {
            get {
                return ResourceManager.GetString("Error_RaisePluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サポートされていない形式のwavファイルです。
        ///このアプリケーションではモノラルのPCMのみサポートしています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_UnsupportedWaveFile {
            get {
                return ResourceManager.GetString("Error_UnsupportedWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析プラグインの読み込みに失敗しました。Pluginsフォルダに壊れたファイルがないか確認の上、アプリケーションを再起動してください
        ///(再度アプリケーションをダウンロードの上、DefaultPlugins以外が存在しない状態での起動を推奨します) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fatal_CannotLoadAudioOperator {
            get {
                return ResourceManager.GetString("Fatal_CannotLoadAudioOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseWindow_OK {
            get {
                return ResourceManager.GetString("LicenseWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報(_A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュのクリア(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ClearCache {
            get {
                return ResourceManager.GetString("MainMenu_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き出し(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Export {
            get {
                return ResourceManager.GetString("MainMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階をSin波として出力(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ExportSineWave {
            get {
                return ResourceManager.GetString("MainMenu_ExportSineWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_HelpMenu {
            get {
                return ResourceManager.GetString("MainMenu_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データの読み込み(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScale {
            get {
                return ResourceManager.GetString("MainMenu_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイルから読み込む(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScaleFromWave {
            get {
                return ResourceManager.GetString("MainMenu_LoadScaleFromWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ManipulationMenu {
            get {
                return ResourceManager.GetString("MainMenu_ManipulationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_OpenFile {
            get {
                return ResourceManager.GetString("MainMenu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Option {
            get {
                return ResourceManager.GetString("MainMenu_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生・停止(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Preview {
            get {
                return ResourceManager.GetString("MainMenu_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ToolMenu {
            get {
                return ResourceManager.GetString("MainMenu_ToolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析・生成プラグインの選択(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_UseOperator {
            get {
                return ResourceManager.GetString("Menu_UseOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析プラグインの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadAudioOperator {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadAudioOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込みプラグインの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadScaleLoader {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadScaleLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   waveファイルの読み込み失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle_CannotLoadWaveFile {
            get {
                return ResourceManager.GetString("MessageBoxTitle_CannotLoadWaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_Cancel {
            get {
                return ResourceManager.GetString("MessageBoxWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_ExceptionInfoHeader {
            get {
                return ResourceManager.GetString("MessageBoxWindow_ExceptionInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_No {
            get {
                return ResourceManager.GetString("MessageBoxWindow_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_OK {
            get {
                return ResourceManager.GetString("MessageBoxWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleError {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleInformation {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleQuestion {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_TitleWarning {
            get {
                return ResourceManager.GetString("MessageBoxWindow_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい(_Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxWindow_Yes {
            get {
                return ResourceManager.GetString("MessageBoxWindow_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※この設定は次回音声読み込み時に反映されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_ApplyTimingLoadWave {
            get {
                return ResourceManager.GetString("OptionWindow_ApplyTimingLoadWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビューのレイテンシ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_Audio_PreviewLatency {
            get {
                return ResourceManager.GetString("OptionWindow_Audio_PreviewLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_Audio_PreviewLatencyUnit {
            get {
                return ResourceManager.GetString("OptionWindow_Audio_PreviewLatencyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_General_DebugGroup {
            get {
                return ResourceManager.GetString("OptionWindow_General_DebugGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージボックスに例外情報が含まれる場合表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_General_ShowException {
            get {
                return ResourceManager.GetString("OptionWindow_General_ShowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フレームサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_PitchOperation_FramePeriod {
            get {
                return ResourceManager.GetString("OptionWindow_PitchOperation_FramePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_PitchOperation_FramePeriodUnit {
            get {
                return ResourceManager.GetString("OptionWindow_PitchOperation_FramePeriodUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_SettingGroupAudio {
            get {
                return ResourceManager.GetString("OptionWindow_SettingGroupAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全般 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_SettingGroupGeneral {
            get {
                return ResourceManager.GetString("OptionWindow_SettingGroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチ調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_SettingGroupPitchOperation {
            get {
                return ResourceManager.GetString("OptionWindow_SettingGroupPitchOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionWindow_Title {
            get {
                return ResourceManager.GetString("OptionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_AnalyzingWave {
            get {
                return ResourceManager.GetString("ProgressMessage_AnalyzingWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル出力中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_ExportWave {
            get {
                return ResourceManager.GetString("ProgressMessage_ExportWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadScale {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadWave {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveBits_Bit16 {
            get {
                return ResourceManager.GetString("WaveBits_Bit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   24bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveBits_Bit24 {
            get {
                return ResourceManager.GetString("WaveBits_Bit24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32bit(浮動小数) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveBits_Bit32 {
            get {
                return ResourceManager.GetString("WaveBits_Bit32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveBits_Bit8 {
            get {
                return ResourceManager.GetString("WaveBits_Bit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_CancelButton {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス「{0}」にファイルを保存することは出来ません。ディレクトリ「{1}」が存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_DirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_DirectoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス「{0}」にファイルを保存することは出来ません。ファイル名がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_EmptyFileNameMessage {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_EmptyFileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先のパスを空にすることは出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_EmptySavePathMessage {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_EmptySavePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス「{0}」にファイルを保存することは出来ません。パスが不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_InvalidSavePathMessage {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_InvalidSavePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力Bit数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_OutputBits {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_OutputBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル「{0}」は既に存在します。上書きしますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_OverWriteCautionMessage {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_OverWriteCautionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_OverWriteTitle {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_OverWriteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_SaveButton {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_SavePath {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_SelectPathButton {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_SelectPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き出し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaveExportSettingWindow_Title {
            get {
                return ResourceManager.GetString("WaveExportSettingWindow_Title", resourceCulture);
            }
        }
    }
}
