//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervallo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervallo.Properties.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   編集(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き出し(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Export {
            get {
                return ResourceManager.GetString("MainMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データの読み込み(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScale {
            get {
                return ResourceManager.GetString("MainMenu_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイルから読み込む(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_LoadScaleFromWave {
            get {
                return ResourceManager.GetString("MainMenu_LoadScaleFromWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_ManipulationMenu {
            get {
                return ResourceManager.GetString("MainMenu_ManipulationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_OpenFile {
            get {
                return ResourceManager.GetString("MainMenu_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Preview {
            get {
                return ResourceManager.GetString("MainMenu_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声解析中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_AnalyzingWave {
            get {
                return ResourceManager.GetString("ProgressMessage_AnalyzingWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル出力中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_ExportWave {
            get {
                return ResourceManager.GetString("ProgressMessage_ExportWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音階データ読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadScale {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wavファイル読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressMessage_LoadWave {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadWave", resourceCulture);
            }
        }
    }
}
