using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Intervallo.DefaultPlugins.Vsqx
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     このコードはツールによって生成されました。
    //     ランタイム バージョン:4.0.30319.42000
    //
    //     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
    //     コードが再生成されるときに損失したりします。
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // このソース コードは xsd によって自動生成されました。Version=4.6.1055.0 です。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vsq4 : IVsqx
    {

        private string venderField;

        private string versionField;

        private vVoice[] vVoiceTableField;

        private mixer mixerField;

        private masterTrack masterTrackField;

        private vsTrack[] vsTrackField;

        private wavPart[] monoTrackField;

        private wavPart[] stTrackField;

        private aux[] auxField;

        /// <remarks/>
        public string vender
        {
            get
            {
                return this.venderField;
            }
            set
            {
                this.venderField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vVoice", IsNullable = false)]
        public vVoice[] vVoiceTable
        {
            get
            {
                return this.vVoiceTableField;
            }
            set
            {
                this.vVoiceTableField = value;
            }
        }

        /// <remarks/>
        public mixer mixer
        {
            get
            {
                return this.mixerField;
            }
            set
            {
                this.mixerField = value;
            }
        }

        /// <remarks/>
        public masterTrack masterTrack
        {
            get
            {
                return this.masterTrackField;
            }
            set
            {
                this.masterTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vsTrack")]
        public vsTrack[] vsTrack
        {
            get
            {
                return this.vsTrackField;
            }
            set
            {
                this.vsTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wavPart", IsNullable = false)]
        public wavPart[] monoTrack
        {
            get
            {
                return this.monoTrackField;
            }
            set
            {
                this.monoTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wavPart", IsNullable = false)]
        public wavPart[] stTrack
        {
            get
            {
                return this.stTrackField;
            }
            set
            {
                this.stTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aux")]
        public aux[] aux
        {
            get
            {
                return this.auxField;
            }
            set
            {
                this.auxField = value;
            }
        }

        [XmlIgnore]
        public IVSMasterTrack MasterTrack => masterTrackField;

        [XmlIgnore]
        public IVSTrack[] VSTrack => vsTrackField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vVoice
    {

        private byte bsField;

        private byte pcField;

        private string idField;

        private string nameField;

        private vPrm vPrmField;

        private string id2Field;

        private vPrm2 vPrm2Field;

        /// <remarks/>
        public byte bs
        {
            get
            {
                return this.bsField;
            }
            set
            {
                this.bsField = value;
            }
        }

        /// <remarks/>
        public byte pc
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public vPrm vPrm
        {
            get
            {
                return this.vPrmField;
            }
            set
            {
                this.vPrmField = value;
            }
        }

        /// <remarks/>
        public string id2
        {
            get
            {
                return this.id2Field;
            }
            set
            {
                this.id2Field = value;
            }
        }

        /// <remarks/>
        public vPrm2 vPrm2
        {
            get
            {
                return this.vPrm2Field;
            }
            set
            {
                this.vPrm2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vPrm
    {

        private sbyte breField;

        private sbyte briField;

        private sbyte cleField;

        private sbyte genField;

        private sbyte opeField;

        /// <remarks/>
        public sbyte bre
        {
            get
            {
                return this.breField;
            }
            set
            {
                this.breField = value;
            }
        }

        /// <remarks/>
        public sbyte bri
        {
            get
            {
                return this.briField;
            }
            set
            {
                this.briField = value;
            }
        }

        /// <remarks/>
        public sbyte cle
        {
            get
            {
                return this.cleField;
            }
            set
            {
                this.cleField = value;
            }
        }

        /// <remarks/>
        public sbyte gen
        {
            get
            {
                return this.genField;
            }
            set
            {
                this.genField = value;
            }
        }

        /// <remarks/>
        public sbyte ope
        {
            get
            {
                return this.opeField;
            }
            set
            {
                this.opeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    public partial class typePhonemes
    {

        private byte lockField;

        private bool lockFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte @lock
        {
            get
            {
                return this.lockField;
            }
            set
            {
                this.lockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockSpecified
        {
            get
            {
                return this.lockFieldSpecified;
            }
            set
            {
                this.lockFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    public partial class typeParamAttr : IVSTypeParamAttr
    {

        private string idField;

        private int valueField;

        [XmlIgnore]
        public string ID => idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vPrm2
    {

        private sbyte breField;

        private sbyte briField;

        private sbyte cleField;

        private sbyte genField;

        private sbyte opeField;

        private sbyte volField;

        /// <remarks/>
        public sbyte bre
        {
            get
            {
                return this.breField;
            }
            set
            {
                this.breField = value;
            }
        }

        /// <remarks/>
        public sbyte bri
        {
            get
            {
                return this.briField;
            }
            set
            {
                this.briField = value;
            }
        }

        /// <remarks/>
        public sbyte cle
        {
            get
            {
                return this.cleField;
            }
            set
            {
                this.cleField = value;
            }
        }

        /// <remarks/>
        public sbyte gen
        {
            get
            {
                return this.genField;
            }
            set
            {
                this.genField = value;
            }
        }

        /// <remarks/>
        public sbyte ope
        {
            get
            {
                return this.opeField;
            }
            set
            {
                this.opeField = value;
            }
        }

        /// <remarks/>
        public sbyte vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class mixer
    {

        private masterUnit masterUnitField;

        private vsUnit[] vsUnitField;

        private monoUnit monoUnitField;

        private stUnit stUnitField;

        /// <remarks/>
        public masterUnit masterUnit
        {
            get
            {
                return this.masterUnitField;
            }
            set
            {
                this.masterUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vsUnit")]
        public vsUnit[] vsUnit
        {
            get
            {
                return this.vsUnitField;
            }
            set
            {
                this.vsUnitField = value;
            }
        }

        /// <remarks/>
        public monoUnit monoUnit
        {
            get
            {
                return this.monoUnitField;
            }
            set
            {
                this.monoUnitField = value;
            }
        }

        /// <remarks/>
        public stUnit stUnit
        {
            get
            {
                return this.stUnitField;
            }
            set
            {
                this.stUnitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class masterUnit
    {

        private short oDevField;

        private plug[] plugField;

        private plugSR plugSRField;

        private int rLvlField;

        private int volField;

        /// <remarks/>
        public short oDev
        {
            get
            {
                return this.oDevField;
            }
            set
            {
                this.oDevField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plug")]
        public plug[] plug
        {
            get
            {
                return this.plugField;
            }
            set
            {
                this.plugField = value;
            }
        }

        /// <remarks/>
        public plugSR plugSR
        {
            get
            {
                return this.plugSRField;
            }
            set
            {
                this.plugSRField = value;
            }
        }

        /// <remarks/>
        public int rLvl
        {
            get
            {
                return this.rLvlField;
            }
            set
            {
                this.rLvlField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class plug
    {

        private string idField;

        private string nameField;

        private byte sdkVerField;

        private int nPrmField;

        private int[] vPrmField;

        private int presetNoField;

        private bool presetNoFieldSpecified;

        private byte enableField;

        private byte bypassField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public byte sdkVer
        {
            get
            {
                return this.sdkVerField;
            }
            set
            {
                this.sdkVerField = value;
            }
        }

        /// <remarks/>
        public int nPrm
        {
            get
            {
                return this.nPrmField;
            }
            set
            {
                this.nPrmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("v", IsNullable = false)]
        public int[] vPrm
        {
            get
            {
                return this.vPrmField;
            }
            set
            {
                this.vPrmField = value;
            }
        }

        /// <remarks/>
        public int presetNo
        {
            get
            {
                return this.presetNoField;
            }
            set
            {
                this.presetNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presetNoSpecified
        {
            get
            {
                return this.presetNoFieldSpecified;
            }
            set
            {
                this.presetNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte enable
        {
            get
            {
                return this.enableField;
            }
            set
            {
                this.enableField = value;
            }
        }

        /// <remarks/>
        public byte bypass
        {
            get
            {
                return this.bypassField;
            }
            set
            {
                this.bypassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class plugSR
    {

        private string idField;

        private string nameField;

        private byte sdkVerField;

        private int nPrmField;

        private int[] vPrmField;

        private int presetNoField;

        private bool presetNoFieldSpecified;

        private byte enableField;

        private byte bypassField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public byte sdkVer
        {
            get
            {
                return this.sdkVerField;
            }
            set
            {
                this.sdkVerField = value;
            }
        }

        /// <remarks/>
        public int nPrm
        {
            get
            {
                return this.nPrmField;
            }
            set
            {
                this.nPrmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("v", IsNullable = false)]
        public int[] vPrm
        {
            get
            {
                return this.vPrmField;
            }
            set
            {
                this.vPrmField = value;
            }
        }

        /// <remarks/>
        public int presetNo
        {
            get
            {
                return this.presetNoField;
            }
            set
            {
                this.presetNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presetNoSpecified
        {
            get
            {
                return this.presetNoFieldSpecified;
            }
            set
            {
                this.presetNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte enable
        {
            get
            {
                return this.enableField;
            }
            set
            {
                this.enableField = value;
            }
        }

        /// <remarks/>
        public byte bypass
        {
            get
            {
                return this.bypassField;
            }
            set
            {
                this.bypassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vsUnit
    {

        private byte tNoField;

        private int iGinField;

        private plug[] plugField;

        private int sLvlField;

        private byte sEnableField;

        private byte mField;

        private byte sField;

        private int panField;

        private int volField;

        /// <remarks/>
        public byte tNo
        {
            get
            {
                return this.tNoField;
            }
            set
            {
                this.tNoField = value;
            }
        }

        /// <remarks/>
        public int iGin
        {
            get
            {
                return this.iGinField;
            }
            set
            {
                this.iGinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plug")]
        public plug[] plug
        {
            get
            {
                return this.plugField;
            }
            set
            {
                this.plugField = value;
            }
        }

        /// <remarks/>
        public int sLvl
        {
            get
            {
                return this.sLvlField;
            }
            set
            {
                this.sLvlField = value;
            }
        }

        /// <remarks/>
        public byte sEnable
        {
            get
            {
                return this.sEnableField;
            }
            set
            {
                this.sEnableField = value;
            }
        }

        /// <remarks/>
        public byte m
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }

        /// <remarks/>
        public byte s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }

        /// <remarks/>
        public int pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class monoUnit
    {

        private int iGinField;

        private plug[] plugField;

        private int sLvlField;

        private byte sEnableField;

        private byte mField;

        private byte sField;

        private int panField;

        private int volField;

        /// <remarks/>
        public int iGin
        {
            get
            {
                return this.iGinField;
            }
            set
            {
                this.iGinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plug")]
        public plug[] plug
        {
            get
            {
                return this.plugField;
            }
            set
            {
                this.plugField = value;
            }
        }

        /// <remarks/>
        public int sLvl
        {
            get
            {
                return this.sLvlField;
            }
            set
            {
                this.sLvlField = value;
            }
        }

        /// <remarks/>
        public byte sEnable
        {
            get
            {
                return this.sEnableField;
            }
            set
            {
                this.sEnableField = value;
            }
        }

        /// <remarks/>
        public byte m
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }

        /// <remarks/>
        public byte s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }

        /// <remarks/>
        public int pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class stUnit
    {

        private int iGinField;

        private plug[] plugField;

        private byte mField;

        private byte sField;

        private int volField;

        /// <remarks/>
        public int iGin
        {
            get
            {
                return this.iGinField;
            }
            set
            {
                this.iGinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plug")]
        public plug[] plug
        {
            get
            {
                return this.plugField;
            }
            set
            {
                this.plugField = value;
            }
        }

        /// <remarks/>
        public byte m
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }

        /// <remarks/>
        public byte s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class masterTrack : IVSMasterTrack
    {

        private string seqNameField;

        private string commentField;

        private ushort resolutionField;

        private byte preMeasureField;

        private timeSig[] timeSigField;

        private tempo[] tempoField;

        /// <remarks/>
        public string seqName
        {
            get
            {
                return this.seqNameField;
            }
            set
            {
                this.seqNameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public ushort resolution
        {
            get
            {
                return this.resolutionField;
            }
            set
            {
                this.resolutionField = value;
            }
        }

        /// <remarks/>
        public byte preMeasure
        {
            get
            {
                return this.preMeasureField;
            }
            set
            {
                this.preMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("timeSig")]
        public timeSig[] timeSig
        {
            get
            {
                return this.timeSigField;
            }
            set
            {
                this.timeSigField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tempo")]
        public tempo[] tempo
        {
            get
            {
                return this.tempoField;
            }
            set
            {
                this.tempoField = value;
            }
        }

        [XmlIgnore]
        public ushort Resolution => resolutionField;

        [XmlIgnore]
        public byte PreMeasure => preMeasureField;

        [XmlIgnore]
        public IVSTimeSig[] TimeSig => timeSigField;

        [XmlIgnore]
        public IVSTempo[] Tempo => tempoField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class timeSig : IVSTimeSig
    {

        private int mField;

        private byte nuField;

        private byte deField;

        /// <remarks/>
        public int m
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }

        /// <remarks/>
        public byte nu
        {
            get
            {
                return this.nuField;
            }
            set
            {
                this.nuField = value;
            }
        }

        /// <remarks/>
        public byte de
        {
            get
            {
                return this.deField;
            }
            set
            {
                this.deField = value;
            }
        }

        [XmlIgnore]
        public int Measure => mField;

        [XmlIgnore]
        public byte Nume => nuField;

        [XmlIgnore]
        public byte Denominator => deField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class tempo : IVSTempo
    {

        private int tField;

        private int vField;

        [XmlIgnore]
        public int BPM => vField;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        [XmlIgnore]
        public int Tick
        {
            get
            {
                return tField;
            }
            set
            {
                tField = value;
            }
        }

        /// <remarks/>
        public int v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vsTrack : IVSTrack
    {

        private byte tNoField;

        private string nameField;

        private string commentField;

        private vsPart[] vsPartField;

        /// <remarks/>
        public byte tNo
        {
            get
            {
                return this.tNoField;
            }
            set
            {
                this.tNoField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vsPart")]
        public vsPart[] vsPart
        {
            get
            {
                return this.vsPartField;
            }
            set
            {
                this.vsPartField = value;
            }
        }

        [XmlIgnore]
        public IVSPart[] Part => vsPartField;

        [XmlIgnore]
        public string Name => nameField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vsPart : IVSPart
    {

        private int tField;

        private int playTimeField;

        private string nameField;

        private string commentField;

        private sPlug sPlugField;

        private typeParamAttr[] pStyleField;

        private singer[] singerField;

        private cc[] ccField;

        private note[] noteField;

        private byte planeField;

        private bool planeFieldSpecified;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public int playTime
        {
            get
            {
                return this.playTimeField;
            }
            set
            {
                this.playTimeField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public sPlug sPlug
        {
            get
            {
                return this.sPlugField;
            }
            set
            {
                this.sPlugField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("v", IsNullable = false)]
        public typeParamAttr[] pStyle
        {
            get
            {
                return this.pStyleField;
            }
            set
            {
                this.pStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("singer")]
        public singer[] singer
        {
            get
            {
                return this.singerField;
            }
            set
            {
                this.singerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cc")]
        public cc[] cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note")]
        public note[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public byte plane
        {
            get
            {
                return this.planeField;
            }
            set
            {
                this.planeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool planeSpecified
        {
            get
            {
                return this.planeFieldSpecified;
            }
            set
            {
                this.planeFieldSpecified = value;
            }
        }

        [XmlIgnore]
        public int Tick => tField;

        [XmlIgnore]
        public int PlayTime => playTimeField;

        [XmlIgnore]
        public IVSControlChange[] CC => ccField;

        [XmlIgnore]
        public IVSNote[] Note => noteField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class sPlug
    {

        private string idField;

        private string nameField;

        private string versionField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class singer
    {

        private int tField;

        private byte bsField;

        private byte pcField;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public byte bs
        {
            get
            {
                return this.bsField;
            }
            set
            {
                this.bsField = value;
            }
        }

        /// <remarks/>
        public byte pc
        {
            get
            {
                return this.pcField;
            }
            set
            {
                this.pcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class cc : IVSControlChange
    {

        private int tField;

        private typeParamAttr vField;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        [XmlIgnore]
        public int Tick => tField;

        /// <remarks/>
        public typeParamAttr v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }

        [XmlIgnore]
        public IVSTypeParamAttr Attr => vField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class note : IVSNote
    {

        private int tField;

        private int durField;

        private byte nField;

        private byte vField;

        private string yField;

        private typePhonemes pField;

        private nStyle nStyleField;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public int dur
        {
            get
            {
                return this.durField;
            }
            set
            {
                this.durField = value;
            }
        }

        /// <remarks/>
        public byte n
        {
            get
            {
                return this.nField;
            }
            set
            {
                this.nField = value;
            }
        }

        /// <remarks/>
        public byte v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }

        /// <remarks/>
        public string y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        public typePhonemes p
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        public nStyle nStyle
        {
            get
            {
                return this.nStyleField;
            }
            set
            {
                this.nStyleField = value;
            }
        }

        [XmlIgnore]
        public int Tick => tField;

        [XmlIgnore]
        public int Duration => durField;

        [XmlIgnore]
        public int NoteNumber => nField;

        [XmlIgnore]
        public IVSNStyle NStyle => nStyleField;

        [XmlIgnore]
        public string Character => yField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class nStyle : IVSNStyle
    {

        private typeParamAttr[] vField;

        private seq[] seqField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("v")]
        public typeParamAttr[] v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seq")]
        public seq[] seq
        {
            get
            {
                return this.seqField;
            }
            set
            {
                this.seqField = value;
            }
        }

        [XmlIgnore]
        public IVSTypeParamAttr[] Attrs => vField;

        [XmlIgnore]
        public IVSSeq[] Sequence => seqField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class seq : IVSSeq
    {

        private seqCC[] ccField;

        private string idField;

        [XmlIgnore]
        public IVSSeqControlChange[] CC => ccField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cc")]
        public seqCC[] cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        [XmlIgnore]
        public string ID => idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    public partial class seqCC : IVSSeqControlChange
    {

        private int pField;

        private int vField;

        /// <remarks/>
        public int p
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        [XmlIgnore]
        public int Position => pField;

        /// <remarks/>
        public int v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }

        [XmlIgnore]
        public int Value => vField;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class wavPart
    {

        private int tField;

        private int playTimeField;

        private string nameField;

        private string commentField;

        private uint fsField;

        private byte rsField;

        private byte nChField;

        private string filePathField;

        /// <remarks/>
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        /// <remarks/>
        public int playTime
        {
            get
            {
                return this.playTimeField;
            }
            set
            {
                this.playTimeField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public uint fs
        {
            get
            {
                return this.fsField;
            }
            set
            {
                this.fsField = value;
            }
        }

        /// <remarks/>
        public byte rs
        {
            get
            {
                return this.rsField;
            }
            set
            {
                this.rsField = value;
            }
        }

        /// <remarks/>
        public byte nCh
        {
            get
            {
                return this.nChField;
            }
            set
            {
                this.nChField = value;
            }
        }

        /// <remarks/>
        public string filePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class aux
    {

        private string idField;

        private string contentField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class vVoiceTable
    {

        private vVoice[] vVoiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vVoice")]
        public vVoice[] vVoice
        {
            get
            {
                return this.vVoiceField;
            }
            set
            {
                this.vVoiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class pStyle
    {

        private typeParamAttr[] vField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("v")]
        public typeParamAttr[] v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class monoTrack
    {

        private wavPart[] wavPartField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wavPart")]
        public wavPart[] wavPart
        {
            get
            {
                return this.wavPartField;
            }
            set
            {
                this.wavPartField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq4/", IsNullable = false)]
    public partial class stTrack
    {

        private wavPart[] wavPartField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wavPart")]
        public wavPart[] wavPart
        {
            get
            {
                return this.wavPartField;
            }
            set
            {
                this.wavPartField = value;
            }
        }
    }
}